### ISSUE TITLE
(Android) GLES 3 version of core is crashing

### ISSUE THREAD

**Issue by fzurita** [GLupeN64/GLupeN64#127]
It seems that the GLES 3 version of the core is crashing when loading games. The GLES2 version of the core seems to be working fine. 

I'll try to gather some debug output later from ADB.

**Comment by loganmc10** [comment]
It's because of RetroArch. RetroArch 1.3.6 doesn't support GLES3 on Android.

If you try one of the nightlies from here it should work:
https://buildbot.libretro.com/nightly/android/

**Comment by fzurita** [comment]
Yeah, I was using the nightly Android build to test. 11/30 one to be specific.

**Comment by loganmc10** [comment]
huh ok then I'm not sure, I just tested and it seems to work for me. This doesn't get a ton of testing on Android owing to the popularity of mupen64plus-ae :P

**Comment by fzurita** [comment]
Hehe. Well, technically, it's not as popular with the general Android community which prefers MegaN64, which is a clone of an older version of mupen64plus-ae.

Mupen64plus-ae does seem more popular with the more knowledgeable emulation community though.

**Comment by fzurita** [comment]
I'm give this a shot with my PC hooked up, maybe I can give you a hint to where the problem lies.

**Comment by orbea** [comment]
I can't reproduce this on my phone either, seems @fzurita will have to try looking at this with logcat. In case this is helpful here are some documentation on using logcat. I like `adb logcat *:W` as it prints just enough information to be useful without flooding the console.
http://adbshell.com/commands/adb-logcat

**Comment by fzurita** [comment]
I found the problem. I had backtrace on GL error enabled. That caused the issue.

**Comment by fzurita** [comment]
There are other issues though. There core is crashing on shutdown. It's also crashing when saving a state.

**Comment by loganmc10** [comment]
What device is this? Also wouldn't the crash with "back trace on GL error" indicate that there is a GL error happening?

**Comment by fzurita** [comment]
This is a ZTE Axon 7. It has an Snapdragon 820 which has an Adreno 530 for a GPU.

The back trace on GL error shouldn't cause the app to crash, it just prints out a back trace to the adb logcat whenever there is a GL error. The current driver has a bug though so that if the back trace on GL error is enabled, the EXT_buffer_storage extension stops being properly supported. In mupen64plus AE, the copies just fail, but I'm thinking that in retroarch, it must be more damaging.

I was able to generate a backtrace on the coredump, but because I don't have a proper workspace setup for retroarch, I'm unable to give you line numbers.

**Comment by loganmc10** [comment]
Oh ok, GLupeN64 uses EXT_buffer_storage for a lot of things (texture uploads, draw commands, vertex array uploads) if it's available so it's not surprising that it doesn't work if that isn't functioning.

Does the backtrace give you any function names or anything? I haven't heard of anyone else having crashes on exit or with savestates, though like I mentioned it probably doesn't get a lot of use on Android.

**Comment by fzurita** [comment]
Another issue I'm seeing. I can't seem to get core settings to stick. Maybe it has to do with enabling per game settings.

**Comment by fzurita** [comment]
Ok, a lot of the issues I was having are probably happening because I installed the play store version of retroarch and the installed the nightly version. The configurations files must not be forward compatible.

**Comment by loganmc10** [comment]
No they are not, a lot of people run into issues when upgrading RetroArch and something has changed, they should probably implement config file revisions that invalidate the config when something has changed that will break it...

It's a somewhat fragile application in general, but I assume the texture corruption is still there?

**Comment by fzurita** [comment]
Yes, texture issues still there.

**Comment by loganmc10** [comment]
hm I'm not sure, @orbea has a phone with an Adreno 405 that supports EXT_buffer_storage and I don't think these issues show up in Super Mario with GLES3 there do they @orbea ?

I don't actually own a device that supports EXT_buffer_storage, so it's hard for me to test, besides testing the desktop version with ARB_buffer_storage.

**Comment by loganmc10** [comment]
The only real difference between this plugin and GLideN64 is that I use EXT/ARB_buffer_storage quite extensively, and I use glTexStorage2D instead of glTexImage. I don't know if there is much of a performance difference if any, it is mostly because Linux doesn't allow client side vertex arrays, so ARB_buffer_storage is needed to get it working on Linux at the same level of performance as the current method, and I just kept expanding its (ARB_buffer_storage) usage as I went along.

**Comment by fzurita** [comment]
I did notice that you are uploading textures using PBOs.

**Comment by loganmc10** [comment]
Ya, I assume that must lead to some kind of performance increase? For instance, right now when a texture is created, pDest is malloc'ed, written to, and then passed to glTexSubImage, which will copy it to wherever the GPU wants it (it must copy it since you could modify pDest after that call).

With a PBO, pDest is not malloc'ed, it is a pointer into the buffer, so you write the texture data directly into the buffer, and then tell glTexSubImage where in the buffer you wrote it, so glTexSubImage returns immediately without having to copy anything, since the assumption is that you won't modify the buffer contents before it uses the data in the buffer.

**Comment by fzurita** [comment]
Interesting, I enabled textured enhancements and now textures look correct.

**Comment by loganmc10** [comment]
That make sense, because enabling texture enhancements disabled the PBO texture uploading. I don't use PBO texture uploading with texture enhancements since the textures might be quite large (high res textures) and it might overflow the buffer.

Honesty time, I don't use have Fence Syncing or anything.... I just make the buffers large enough (based on my testing and assumptions) that by the time it gets around to overwriting something in the buffer, that part of the buffer has already been used/read.

There is a possibility that the PBO buffer is not large enough, and it is overwriting the texture data with new data before the GPU has had a change to process the original data.

**Comment by fzurita** [comment]
This is a dumb question, but how do you enable the frame limiter so that games are not constantly fast forward?

**Comment by fzurita** [comment]
Ok, I spoke too soon, I tried another game and textures are still very messed up even with texture enhancements.

There are also some depth buffer issues since I can see through walls in Conker's bad fur day.

**Comment by loganmc10** [comment]
I actually need to implement the speed limited (I assume that is what you're referring to?) in mupen64plus-core it uses SDL to keep the time so I just need to re-write it a bit so it doesn't use that.

I'll test Conkers in a bit, I clear the depth buffer (glClear), right after each glBindFramebuffer call. It fixes some devices (like the Raspberry Pi and @orbea's phone) that have weird transparency issues. I've never run into an issue with it, but if you can see through walls that is probably the culprit..

**Comment by orbea** [comment]
@loganmc10 I have not tried Super Mario 64 on my phone before actually. Now that I have I can confirm it seems to work fine. No crashes when starting, closing, making or loading a savestate and I can not reproduce the graphical errors shown in @fzurita 's screenshots.

**Comment by fzurita** [comment]
After clearing my configuration, the only crash I'm getting is when saving save states. @orbea How are you getting around the lack of speed limiter?

**Comment by orbea** [comment]
To be honest I'm not sure. Games just seem to run at the correct speed here by default.

**Comment by loganmc10** [comment]
@fzurita its the same for me, the games seem to run at the correct speed for me as well, I've noticed GoldenEye seems to speed up somewhat at times, but not much

**Comment by fzurita** [comment]
Interesting. I guess it's another issue with my phone. I wonder how the speed is being limited by retroarch? Is it happening because of the audio thread?

Also, aside from the texture, depth buffer, and speed limiter issues. This build of GLideN64/Mupen64Plus does seem to be significantly faster than Mupen64Plus-AE in Mario 64 and Mario Kart 64.

If we can get over those issues, it would definitely be better. It will be great once gonetz can include your VBO and buffer storage changes.

**Comment by loganmc10** [comment]
@orbea I've got bad news for you, that depth buffering clearing stuff is indeed causing the walls in Conkers to be transparent, I've got to revert it, I know I've done this to you before....

It's really a GLideN64 thing, I would take a screenshot of it (from mupen64plus-ae so they know it's not something I've done here) and post an issue with GLideN64.

Maybe @fzurita can figure it out since he's the one that ruined our fun :P

**Comment by loganmc10** [comment]
> Also, aside from the texture, depth buffer, and speed limiter issues. This build of GLideN64/Mupen64Plus does seem to be significantly faster

Sorry for the randomness but that made me think of this lol:
https://www.youtube.com/watch?v=ZKtFIgmoqoI&feature=youtu.be&t=54s

**Comment by fzurita** [comment]
Yeah, depth buffer issues are not present in Mupen64Plus-AE with the latest GLideN64. It's most likely a device specific issue for @orbea phone like it is for PowerVR. Probably a driver version specific fix is needed.

**Comment by loganmc10** [comment]
As for the speed limiter, RetroArch has its own speed limiter:

https://github.com/GLupeN64/GLupeN64/blob/master/libretro/libretro.c#L334

But ya, games seem to run at normal speed for me with or without framebuffer emulation on

**Comment by fzurita** [comment]
Hmm... I wonder why I'm having that issue.

**Comment by fzurita** [comment]
Another thing, for texture filtering, you should add the option to not filter background textures. It's a considerable speed up for some games.

**Comment by loganmc10** [comment]
Ok the background filtering option and the depth issues should be fixed, it takes a while to make its way to the Online Updater though.

I'll need to look into the speed limiter and texture issues. There is a chance I may acquire a Shield Tablet soonish and that supports EXT_buffer_storage so I could test it there.

I've never run into any speed limiter issues on desktop or mobile tough, like how fast are we talking? I've played on a desktop with a Nvidia GPU, certainly powerful enough to run Super Mario 64 way faster than normal, and it runs at a normal speed.

**Comment by orbea** [comment]
@loganmc10 It would be really nice if there was a proper fix for the buffer clearing in GLideN64 (Rather a proper fix in the driver, but I'm not holding my breath). I will have to look into building mupen64plus-ae from source, but it may take some time since android studio is a pain in the ass unlike your Makefile.

That said I can reproduce graphical errors here with Conker's Bad Fur Day. These include depth buffer issues, strange blue circles that follow Conker around, lighting issues and graphics that do not update correctly (The nintendo logo). Its also very slow here...

**Comment by fzurita** [comment]
My speed limiter issue somehow magically fixed itself. I'm not sure what I did to fix it other going through the audio settings maybe.....

**Comment by loganmc10** [comment]
@fzurita I would also like to understand how RetroArch works lol, it's quite complex and rapidly changing, so it's not the most stable solution to build on top of but for some reason I'm drawn to it...

@orbea Conkers is very slow for me on my phone as well, just a tough game to emulate I suppose.

It's going to be hard for me to diagnose what is wrong with the texture uploads, but I'll look into it a bit.

**Comment by orbea** [comment]
I tested the latest commit with GLES3 and here is the current status of my phone.

1. Ocarina of Time is broken again.
2. Super Smash Bros still works fine.
3. Super Mario 64 still works.
4. Conker's Bad Fur Day has improved to some degree. The nintendo logo is now correctly updating, the depth buffer issues are gone, and the strange blue circle is gone. However the depth buffer issues reintroduced themselves in the shadows and the lighting issues still exist.

**Comment by loganmc10** [comment]
Ocarina of Time should work relatively well with Framebuffer Emulation disabled (which should fix the depth issues), just the pause screen animation probably won't work right with Framebuffer Emulation disabled (I know this is a permanent solution, just saying so you can play the game for now)

**Comment by fzurita** [comment]
@orbea Unfortunately I don't have a good set of documentation on how to build Mupen64Plus-AE. I'll document it here though.

* Download Android Studio 2.2
* Download all the bloated mess that you need using the SDK manager. Things that I know are required are the NDK, Android support libraries, the latest API level repositories.
* clone mupen64plus-ae to your hard disk
* Open the cloned project from your hard disk directly from Android Studio.
* From Android Studio choose the Build menu and select "Refresh Linked C++ projects"
* Assuming you already have ADB setup, hook up your phone, select the Run menu, and select "Run 'app'".
* If you missed something from the SDK manager you will be able to tell at this point due to any build errors.

One note, if for some reason Android Studio has problems building the C/C++ projects, delete the app/build/intermediates/ndkBuild directory and then from Android Studio choose the Build menu and select "Refresh Linked C++ projects" again.

**Comment by fzurita** [comment]
I tried the latest. Depth issues seem to be fixed. Texture issues still there.

Also, Conker seems to run a lot slower than Mupen64Plus-AE. Probably because of the higher VIRefresh value for that game.

**Comment by fzurita** [comment]
Another thing, save states do work fine on the regular Mupen64Plus core.

**Comment by loganmc10** [comment]
The ViRefresh was an upstream change, shouldn't it be 2200 for both emulators on that game?

**Comment by fzurita** [comment]
I skipped that change since I thought it would make the game run slower in Android since Android can barely keep up when it's at 1500.

**Comment by loganmc10** [comment]
That's interesting, I would have thought it would do the opposite based on this comment:

https://github.com/mupen64plus/mupen64plus-core/issues/139#issuecomment-174455053

Is the folder where you have your ROMs writeable? It should have a GLupeN64 folder with 2 ini files and a "shaders" folder inside

**Comment by fzurita** [comment]
It's not writable because it's in my external sdcard card and RetroArch hasn't asked for permission to write to it.

**Comment by fzurita** [comment]
Vi refresh overclocks the R4300. So if your device is fast enough to emulate a faster R4300, them games can run smoother, if your device can't handle it, it will have the opposite effect.

**Comment by loganmc10** [comment]
K well that is why the save states are crashing. Also, it won't have written a mupen64plus.ini so it's not using 2200 for Conkers.

Ill need to talk to the RetroArch people about this

**Comment by loganmc10** [comment]
If your ROM directory is not writable then where is RetroArch saving state files and srm (save) files?

**Comment by fzurita** [comment]
Ok, if it's not the ViRefresh, I wonder why it feels so much slower.

**Comment by fzurita** [comment]
I configured it to use a custom directory in the directories config

**Comment by loganmc10** [comment]
Isn't this enough to allow it to write?

https://github.com/libretro/RetroArch/blob/master/pkg/android/phoenix/AndroidManifest.xml#L13

**Comment by fzurita** [comment]
Only for internal storage. For external storage the app has to ask for permissions.

**Comment by loganmc10** [comment]
Ok well I'm not an Android App expert so I'll need to chat with the RetroArch team about that. To test if that is really the problem you can change the RetroArch "System" directory to somewhere that is writable.

Settings -> Directory -> System/BIOS

That location needs to be writable for the save states to work and for mupen64plus.ini and GLideN64.custom.ini to be usable

**Comment by fzurita** [comment]
OK, that worked, now I save states are working. Why are you using that path for save states instead of the save state path?

**Comment by loganmc10** [comment]
It doesn't actually write the save state there, it writes a temporary file. In order to properly follow the way mupen64plus handles save states without custom code I have mupen64plus write the save state there and then I have RetroArch read that file as the source for its save state and then delete it

It's a little strange but it allows me to use the vanilla upstream save state code. A writable RetroArch "system" directory is a reasonable assumption from a RetroArch point of view

**Comment by fzurita** [comment]
Gotcha, I understand now.

**Comment by loganmc10** [comment]
Ok I've broken this up into the remaining issues, so I'll close this, feel free to open another issue if there is something else:

https://github.com/GLupeN64/GLupeN64/issues/130
https://github.com/GLupeN64/GLupeN64/issues/129
https://github.com/libretro/RetroArch/issues/4150

**Comment by fzurita** [comment]
Ok
